name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  ci:
    name: Preside CI
    runs-on: ubuntu-latest
    env:
      luceeVersion: zero-6.0.0.503-SNAPSHOT
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: lucee-script-runner-maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v3
        with:
          path: _actions/lucee/script-runner/main/lucee-download-cache
          key: lucee-downloads
      - name: set passwords, this shouldn't be so manual
        run: |
            pwd
            mkdir -p /home/runner/work/LDEV-4620/LDEV-4620/WEB-INF/lucee-server/context
            echo "password" > /home/runner/work/LDEV-4620/LDEV-4620/WEB-INF/lucee-server/context/password.txt
            #cat /home/runner/work/LDEV-4620/LDEV-4620/WEB-INF/lucee-server/context/password.txt
            mkdir -p /home/runner/work/_actions/lucee/script-runner/main/temp/lucee/lucee-server/context
            echo "password" > /home/runner/work/_actions/lucee/script-runner/main/temp/lucee/lucee-server/context/password.txt
            #cat /home/runner/work/_actions/lucee/script-runner/main/temp/lucee/lucee-server/context/password.txt
            
            ls -lR
      - name: test with script runner
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/tests
          execute: /index.cfm
          luceeVersion: ${{ env.luceeVersion }}
          extensionDir:
          extensions:

    #  - name: Install dependencies
     #   uses: pixl8/github-action-box-install@v2
      #  with:
       #   verbose: true
        #  force: true
      - name: Run tests - 6.0.0.492
        uses: pixl8/github-action-box-test@v3
        with:
          boxjson_dir: /tests
          test_dir: /tests
          test_server_json: /tests/server-492.json
          output_file: /tests/test-results.txt
          verbose: true
      - name: Run tests - 6.0.0.503
        uses: pixl8/github-action-box-test@v3
        with:
          boxjson_dir: /tests
          test_dir: /tests
          test_server_json: /tests/server.json
          output_file: /tests/test-results.txt
          verbose: true
