name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  ci:
    name: Preside CI
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: pixl8/github-action-box-install@v2
        with:
          verbose: true
          force: true
      - name: Run tests
        uses: pixl8/github-action-box-test@v3
        with:
          boxjson_dir: /tests
          test_dir: /tests
          test_server_json: /tests/server.json
          output_file: /tests/test-results.txt
          verbose: false
